namespace SiogaApiPide.Domain
{
    public class Reniec
    {
        public string numeroDni { get; set; }
        public string digitoVerificacion { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string apellidoCasada { get; set; }
        public string apellidoMaternoApp { get; set; }
        public string nombres { get; set; }
        public string codigoUbigeoContinenteDomicilio { get; set; }
        public string codigoUbigeoPaisDomicilio { get; set; }
        public string codigoUbigeoDepartamentoDomicilio { get; set; }
        public string codigoUbigeoProvinciaDomicilio { get; set; }
        public string codigoUbigeoDistritoDomicilio { get; set; }
        public string continenteDomicilio { get; set; }
        public string paisDomicilio { get; set; }
        public string departamentoDomicilio { get; set; }
        public string provinciaDomicilio { get; set; }
        public string distritoDomicilio { get; set; }
        public string codigoEstadoCivil { get; set; }
        public string descripcionEstadoCivil { get; set; }
        public string codigoGradoInstruccion { get; set; }
        public string descripcionGradoInstruccion { get; set; }
        public string estatura { get; set; }
        public string sexo { get; set; }
        public string descripcionSexo { get; set; }
        public string codigoDocumentoSustentatorio { get; set; }
        public string descripcionDocumentoSustentatorio { get; set; }
        public string numeroDocumentoSustentatorio { get; set; }
        public string codigoUbigeoContinenteNacimiento { get; set; }
        public string codigoUbigeoPaisNacimiento { get; set; }
        public string codigoUbigeoDepartamentoNacimiento { get; set; }
        public string codigoUbigeoProvinciaNacimiento { get; set; }
        public string codigoUbigeoDistritoNacimiento { get; set; }
        public string continenteNacimiento { get; set; }
        public string paisNacimiento { get; set; }
        public string departamentoNacimiento { get; set; }
        public string provinciaNacimiento { get; set; }
        public string distritoNacimiento { get; set; }
        public string fechaNacimiento { get; set; }
        public string nombrePadre { get; set; }
        public string nombreMadre { get; set; }
        public string fechaInscripcion { get; set; }
        public string fechaExpedicion { get; set; }
        public string codigoConstanciaVotacion { get; set; }
        public string descripcionConstanciaVotacion { get; set; }
        public string fechaCaducidad { get; set; }
        public string codigoRestriccion { get; set; }
        public string descripcionRestriccion { get; set; }
        public string codigoGrupoRestriccion { get; set; }
        public string descripcionGrupoRestriccion { get; set; }
        public string codigoPrefijoDireccion { get; set; }
        public string descripcionPrefijoDireccion { get; set; }
        public string direccion { get; set; }
        public string numeroDireccion { get; set; }
        public string blockChalet { get; set; }
        public string interior { get; set; }
        public string urbanizacion { get; set; }
        public string etapa { get; set; }
        public string manzana { get; set; }
        public string lote { get; set; }
        public string codigoPrefijoBlockChalet { get; set; }
        public string descripcionPrefijoBlockChalet { get; set; }
        public string codigoPrefijoDptoPisoInterior { get; set; }
        public string descripcionPrefijoDptoPisoInterior { get; set; }
        public string codigoPrefijoUrbCondResid { get; set; }
        public string descripcionPrefijoUrbCondResid { get; set; }
        public string domicilioApp { get; set; }
        public string nombreCompleto { get; set; }
    }
}
